# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="2f47c0c6-4d02-47d8-a5b6-c95065f02e52"
# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -mgbardakov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always